name: PyTest
on:
  push:
    branches:
      - after_paper
jobs:
  test:
    name: Test RadText
    runs-on: ubuntu-latest
    strategy:
#      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - name: Chgeckout repository code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt install install python3 python3-dev build-essential default-java
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install packages
        run: |
          python radtext/cmd/download.py all

      - name: Test with pytest and generate coverage report
        run: |
          pip install pytest pytest-cov
          pytest --cov-report=xml

#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v1.0.2
#       with:
#         token: ${{secrets.CODECOV_TOKEN}}
#         file: ./coverage.xml
#         name: codecov-umbrella
