name: PyTest
on:
  push:
    branches:
      - after_paper
jobs:
  test:
    name: Test RadText
    runs-on: ubuntu-latest
    strategy:
#      max-parallel: 4
      matrix:
        python-version: [3.7]
    env:
      PYTHONPATH: .
    steps:
      - name: Chgeckout repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
          
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get install python3-dev build-essential
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install packages
        run: |
          python -m spacy download en_core_web_sm
          python radtext/cmd/download.py all

      - name: Test with pytest and generate coverage report
        run: |
          pip install pytest 
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml tests

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage/reports/
          fail_ci_if_error: true
          files: ./coverage1.xml,./coverage2.xml
          flags: unittests
          name: codecov-umbrella
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

#     - name: Upload coverage to Codecov
#       uses: codecov/codecov-action@v1.0.2
#       with:
#         token: ${{secrets.CODECOV_TOKEN}}
#         file: ./coverage.xml
#         name: codecov-umbrella
